### ISSUE TITLE
Image Retrieval in Practical Applications 

### ISSUE THREAD

**Issue by Dreamupers** [liyunqianggyn/Deep-Unsupervised-Image-Hashing#2]
The Bi-half layer you proposed to maximize bit entropy is very clever, but I have a question about that:
  In most case, the query image is one picture rather than a minibatch images generated by dataloader in actual retrieval or testing. The Bi-half layer only generate [-1,-1,-1,...] if the input is one image which is useless. In essence, it may do not encourage the network before Bi-half to generate hash codes with maximum bit entropy because it is parameter-free.
  Looking forward for your reply, thanks.

**Comment by liyunqianggyn** [comment]
Thanks for your good question for the paper. During training, we train to align continuous distribution p(u) with the half-half distribution of +1 and −1(bi-half layer). This allows us at test time to simply use the "sign function" as a deterministic function for quantization. Hope it can solve your question.

**Comment by Dreamupers** [comment]
Thanks a lot, I have understood the key role of the custom backward process.

**Comment by pikeyang** [comment]
> Thanks for your good question for the paper. During training, we train to align continuous distribution p(u) with the half-half distribution of +1 and −1(bi-half layer). This allows us at test time to simply use the "sign function" as a deterministic function for quantization. Hope it can solve your question.

Can you provide a detailed explanation of "This allows us at test time to simply use the" sign function "as a deterministic function for quantification"
