### ISSUE TITLE
How to generate the label of image?

### ISSUE THREAD

**Issue by captainfffsama** [liyunqianggyn/Deep-Unsupervised-Image-Hashing#3]
Thanks for you excellent work? I confused about that how to generate the label of image when make a train dataset?

for example, each image in Mscoco has a bin code as train label. How to generate this label on my own image?

**Comment by liyunqianggyn** [comment]
Thank you for your interests:)
This paper focused on unsupervised learning, during training we did not use the label. The label was only used for testing, i.e., computing mAP, precision...
Btw: we did not generate the label by ourself, we use the label provided by the datasets creator.
Please let me know if there is unclear for my explanation.
